<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;

class OrderTemplateExport implements FromCollection, WithHeadings
{
    public function collection()
    {
        return collect([
            [
                'order_number' => 'ORD20250824001',
                'customer_name' => '王小明',
                'customer_phone' => '0912345678',
                'customer_id_number' => 'A123456789',
                'order_type' => '新北長照',
                'service_company' => '太豐',
                'ride_date' => '2025-08-25',
                'ride_time' => '14:30',
                'pickup_county' => '新北市',
                'pickup_district' => '板橋區',
                'pickup_address' => '新北市板橋區民族路100號',
                'dropoff_county' => '台北市',
                'dropoff_district' => '大安區',
                'dropoff_address' => '台北市大安區忠孝東路四段123號',
                'wheelchair' => '是',
                'stair_machine' => '否',
                'companions' => '1',
                'carpool_name' => '李小華',
                'carpool_id' => 'B987654321',
                'driver_name' => '張駕駛',
                'driver_fleet_number' => 'D001',
                'driver_plate_number' => 'ABC-1234',
                'status' => '可派遣',
                'special_status' => '共乘單',
                'remark' => '輪椅乘客，需要協助',
                'created_by' => '管理員',
                'identity' => '市區－一般',
                'created_at' => '2025-08-24 10:30:00',
            ],
            [
                'order_number' => 'ORD20250824002',
                'customer_name' => '陳小美',
                'customer_phone' => '0966777888',
                'customer_id_number' => 'C111222333',
                'order_type' => '台北長照',
                'service_company' => '大立亨',
                'ride_date' => '2025-08-26',
                'ride_time' => '09:00',
                'pickup_county' => '台北市',
                'pickup_district' => '信義區',
                'pickup_address' => '台北市信義區信義路五段456號',
                'dropoff_county' => '新北市',
                'dropoff_district' => '新莊區',
                'dropoff_address' => '新北市新莊區中正路789號',
                'wheelchair' => '否',
                'stair_machine' => '是',
                'companions' => '0',
                'carpool_name' => '',
                'carpool_id' => '',
                'driver_name' => '',
                'driver_fleet_number' => '',
                'driver_plate_number' => '',
                'status' => '已指派',
                'special_status' => '個管單',
                'remark' => '需要爬梯機',
                'created_by' => '客服人員',
                'identity' => '市區－中低收',
                'created_at' => '2025-08-24 11:00:00',
            ],
            [
                'order_number' => '訂單編號（必填，不可重複）',
                'customer_name' => '客戶姓名（必填）',
                'customer_phone' => '客戶電話（必填）',
                'customer_id_number' => '客戶身分證號',
                'order_type' => '訂單類型（新北長照/台北長照/一般乘客等）',
                'service_company' => '服務公司（太豐/大立亨等）',
                'ride_date' => '用車日期（必填，格式：YYYY-MM-DD）',
                'ride_time' => '用車時間（必填，格式：HH:MM）',
                'pickup_county' => '上車縣市（系統自動解析）',
                'pickup_district' => '上車區域（系統自動解析）',
                'pickup_address' => '上車地址（必填，完整地址）',
                'dropoff_county' => '下車縣市（系統自動解析）',
                'dropoff_district' => '下車區域（系統自動解析）',
                'dropoff_address' => '下車地址（必填，完整地址）',
                'wheelchair' => '輪椅需求（是/否/未知）',
                'stair_machine' => '爬梯機需求（是/否/未知）',
                'companions' => '陪同人數（數字）',
                'carpool_name' => '共乘對象姓名（可空白）',
                'carpool_id' => '共乘對象身分證（可空白）',
                'driver_name' => '指派駕駛姓名（可空白）',
                'driver_fleet_number' => '駕駛隊編（可空白）',
                'driver_plate_number' => '車牌號碼（可空白）',
                'status' => '訂單狀態（可派遣/已指派/候補/已取消）',
                'special_status' => '特殊狀態（一般/網頁單/Line/個管單/黑名單/共乘單）',
                'remark' => '備註說明（可空白）',
                'created_by' => '建立者（可空白，預設為系統使用者）',
                'identity' => '身份別（可空白）',
                'created_at' => '建立時間（可空白，系統自動填入）',
            ],
        ]);
    }

    public function headings(): array
    {
        return [
            '訂單編號',
            '客戶姓名',
            '客戶電話',
            '客戶身分證',
            '訂單類型',
            '服務公司',
            '用車日期',
            '用車時間',
            '上車縣市',
            '上車區域',
            '上車地址',
            '下車縣市',
            '下車區域',
            '下車地址',
            '輪椅',
            '爬梯機',
            '陪同人數',
            '共乘姓名',
            '共乘身分證',
            '駕駛姓名',
            '駕駛隊編',
            '車牌號碼',
            '訂單狀態',
            '特殊狀態',
            '備註',
            '建立者',
            '身份別',
            '建立時間',
        ];
    }
}
